C     Diagram 1, Amplitude 1
      DATA MAPCONFIG(   1)/   1/
      DATA (IFOREST(I, -1,   1),I=1,2)/  4,  3/
      DATA SPROP(  -1,   1)/      22/
      DATA (IFOREST(I, -2,   1),I=1,2)/  1,  5/
      DATA TPRID(  -2,   1)/       1/
      DATA (IFOREST(I, -3,   1),I=1,2)/ -2, -1/
C     Diagram 2, Amplitude 2
      DATA MAPCONFIG(   2)/   2/
      DATA (IFOREST(I, -1,   2),I=1,2)/  4,  3/
      DATA SPROP(  -1,   2)/      23/
      DATA (IFOREST(I, -2,   2),I=1,2)/  1,  5/
      DATA TPRID(  -2,   2)/       1/
      DATA (IFOREST(I, -3,   2),I=1,2)/ -2, -1/
C     Diagram 3, Amplitude 3
      DATA MAPCONFIG(   3)/   3/
      DATA (IFOREST(I, -1,   3),I=1,2)/  4,  3/
      DATA SPROP(  -1,   3)/      22/
      DATA (IFOREST(I, -2,   3),I=1,2)/  1, -1/
      DATA TPRID(  -2,   3)/       1/
      DATA (IFOREST(I, -3,   3),I=1,2)/ -2,  5/
C     Diagram 4, Amplitude 4
      DATA MAPCONFIG(   4)/   4/
      DATA (IFOREST(I, -1,   4),I=1,2)/  4,  3/
      DATA SPROP(  -1,   4)/      23/
      DATA (IFOREST(I, -2,   4),I=1,2)/  1, -1/
      DATA TPRID(  -2,   4)/       1/
      DATA (IFOREST(I, -3,   4),I=1,2)/ -2,  5/
C     Number of configs
      DATA MAPCONFIG(0)/   4/
