ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-ckm_no_b_mass'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'UV_3Gt = ', UV_3GT
      WRITE(*,2) 'UV_GQQt = ', UV_GQQT
      WRITE(*,2) 'UVWfct_G_2 = ', UVWFCT_G_2
      WRITE(*,2) 'R2_DDA = ', R2_DDA
      WRITE(*,2) 'R2_UUA = ', R2_UUA
      WRITE(*,2) 'R2_DDZ_V2 = ', R2_DDZ_V2
      WRITE(*,2) 'R2_UUZ_V2 = ', R2_UUZ_V2
      WRITE(*,2) 'R2_UUZ_V5 = ', R2_UUZ_V5
      WRITE(*,2) 'R2_GGHt = ', R2_GGHT
      WRITE(*,2) 'R2_GGZup = ', R2_GGZUP
      WRITE(*,2) 'R2_GGZdown = ', R2_GGZDOWN
      WRITE(*,2) 'R2_GGGZvecUp = ', R2_GGGZVECUP
      WRITE(*,2) 'R2_GGGZvecDown = ', R2_GGGZVECDOWN
      WRITE(*,2) 'R2_GGGZaxialUp = ', R2_GGGZAXIALUP
      WRITE(*,2) 'R2_GGGZaxialDown = ', R2_GGGZAXIALDOWN
      WRITE(*,2) 'R2_GGGAvecUp = ', R2_GGGAVECUP
      WRITE(*,2) 'R2_GGGAvecDown = ', R2_GGGAVECDOWN
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'R2_3Gq = ', R2_3GQ
      WRITE(*,2) 'R2_3Gg = ', R2_3GG
      WRITE(*,2) 'R2_GQQ = ', R2_GQQ
      WRITE(*,2) 'R2_GGq = ', R2_GGQ
      WRITE(*,2) 'R2_GGt = ', R2_GGT
      WRITE(*,2) 'R2_GGg_1 = ', R2_GGG_1
      WRITE(*,2) 'R2_GGg_2 = ', R2_GGG_2
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'UV_3Gg_1eps = ', UV_3GG_1EPS
      WRITE(*,2) 'UV_3Gb_1eps = ', UV_3GB_1EPS
      WRITE(*,2) 'UV_GQQg_1eps = ', UV_GQQG_1EPS
      WRITE(*,2) 'UV_GQQq_1eps = ', UV_GQQQ_1EPS
      WRITE(*,2) 'UVWfct_G_2_1eps = ', UVWFCT_G_2_1EPS
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_21 = ', GC_21
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_1003 = ', GC_1003
