C     Diagram 1, Amplitude 1
      DATA MAPCONFIG(   1)/   1/
      DATA (IFOREST(I, -1,   1),I=1,2)/  4,  3/
      DATA SPROP(  -1,   1)/      22/
      DATA (IFOREST(I, -2,   1),I=1,2)/  6, -1/
      DATA SPROP(  -2,   1)/      -1/
      DATA (IFOREST(I, -3,   1),I=1,2)/  5, -2/
      DATA SPROP(  -3,   1)/      21/
C     Diagram 2, Amplitude 2
      DATA MAPCONFIG(   2)/   2/
      DATA (IFOREST(I, -1,   2),I=1,2)/  4,  3/
      DATA SPROP(  -1,   2)/      22/
      DATA (IFOREST(I, -2,   2),I=1,2)/  5, -1/
      DATA SPROP(  -2,   2)/       1/
      DATA (IFOREST(I, -3,   2),I=1,2)/  6, -2/
      DATA SPROP(  -3,   2)/      21/
C     Diagram 3, Amplitude 3
      DATA MAPCONFIG(   3)/   3/
      DATA (IFOREST(I, -1,   3),I=1,2)/  4,  3/
      DATA SPROP(  -1,   3)/      23/
      DATA (IFOREST(I, -2,   3),I=1,2)/  6, -1/
      DATA SPROP(  -2,   3)/      -1/
      DATA (IFOREST(I, -3,   3),I=1,2)/  5, -2/
      DATA SPROP(  -3,   3)/      21/
C     Diagram 4, Amplitude 4
      DATA MAPCONFIG(   4)/   4/
      DATA (IFOREST(I, -1,   4),I=1,2)/  4,  3/
      DATA SPROP(  -1,   4)/      23/
      DATA (IFOREST(I, -2,   4),I=1,2)/  5, -1/
      DATA SPROP(  -2,   4)/       1/
      DATA (IFOREST(I, -3,   4),I=1,2)/  6, -2/
      DATA SPROP(  -3,   4)/      21/
C     Diagram 5, Amplitude 5
      DATA MAPCONFIG(   5)/   5/
      DATA (IFOREST(I, -1,   5),I=1,2)/  4,  3/
      DATA SPROP(  -1,   5)/      22/
      DATA (IFOREST(I, -2,   5),I=1,2)/  1,  5/
      DATA TPRID(  -2,   5)/       1/
      DATA (IFOREST(I, -3,   5),I=1,2)/ -2, -1/
      DATA TPRID(  -3,   5)/       1/
      DATA (IFOREST(I, -4,   5),I=1,2)/ -3,  6/
C     Diagram 6, Amplitude 6
      DATA MAPCONFIG(   6)/   6/
      DATA (IFOREST(I, -1,   6),I=1,2)/  4,  3/
      DATA SPROP(  -1,   6)/      23/
      DATA (IFOREST(I, -2,   6),I=1,2)/  1,  5/
      DATA TPRID(  -2,   6)/       1/
      DATA (IFOREST(I, -3,   6),I=1,2)/ -2, -1/
      DATA TPRID(  -3,   6)/       1/
      DATA (IFOREST(I, -4,   6),I=1,2)/ -3,  6/
C     Diagram 7, Amplitude 7
      DATA MAPCONFIG(   7)/   7/
      DATA (IFOREST(I, -1,   7),I=1,2)/  4,  3/
      DATA SPROP(  -1,   7)/      22/
      DATA (IFOREST(I, -2,   7),I=1,2)/  6, -1/
      DATA SPROP(  -2,   7)/      -1/
      DATA (IFOREST(I, -3,   7),I=1,2)/  1,  5/
      DATA TPRID(  -3,   7)/       1/
      DATA (IFOREST(I, -4,   7),I=1,2)/ -3, -2/
C     Diagram 8, Amplitude 8
      DATA MAPCONFIG(   8)/   8/
      DATA (IFOREST(I, -1,   8),I=1,2)/  4,  3/
      DATA SPROP(  -1,   8)/      23/
      DATA (IFOREST(I, -2,   8),I=1,2)/  6, -1/
      DATA SPROP(  -2,   8)/      -1/
      DATA (IFOREST(I, -3,   8),I=1,2)/  1,  5/
      DATA TPRID(  -3,   8)/       1/
      DATA (IFOREST(I, -4,   8),I=1,2)/ -3, -2/
C     Diagram 9, Amplitude 9
      DATA MAPCONFIG(   9)/   9/
      DATA (IFOREST(I, -1,   9),I=1,2)/  4,  3/
      DATA SPROP(  -1,   9)/      22/
      DATA (IFOREST(I, -2,   9),I=1,2)/  1,  6/
      DATA TPRID(  -2,   9)/       1/
      DATA (IFOREST(I, -3,   9),I=1,2)/ -2, -1/
      DATA TPRID(  -3,   9)/       1/
      DATA (IFOREST(I, -4,   9),I=1,2)/ -3,  5/
C     Diagram 10, Amplitude 10
      DATA MAPCONFIG(  10)/  10/
      DATA (IFOREST(I, -1,  10),I=1,2)/  4,  3/
      DATA SPROP(  -1,  10)/      23/
      DATA (IFOREST(I, -2,  10),I=1,2)/  1,  6/
      DATA TPRID(  -2,  10)/       1/
      DATA (IFOREST(I, -3,  10),I=1,2)/ -2, -1/
      DATA TPRID(  -3,  10)/       1/
      DATA (IFOREST(I, -4,  10),I=1,2)/ -3,  5/
C     Diagram 11, Amplitude 11
      DATA MAPCONFIG(  11)/  11/
      DATA (IFOREST(I, -1,  11),I=1,2)/  4,  3/
      DATA SPROP(  -1,  11)/      22/
      DATA (IFOREST(I, -2,  11),I=1,2)/  5, -1/
      DATA SPROP(  -2,  11)/       1/
      DATA (IFOREST(I, -3,  11),I=1,2)/  1,  6/
      DATA TPRID(  -3,  11)/       1/
      DATA (IFOREST(I, -4,  11),I=1,2)/ -3, -2/
C     Diagram 12, Amplitude 12
      DATA MAPCONFIG(  12)/  12/
      DATA (IFOREST(I, -1,  12),I=1,2)/  4,  3/
      DATA SPROP(  -1,  12)/      23/
      DATA (IFOREST(I, -2,  12),I=1,2)/  5, -1/
      DATA SPROP(  -2,  12)/       1/
      DATA (IFOREST(I, -3,  12),I=1,2)/  1,  6/
      DATA TPRID(  -3,  12)/       1/
      DATA (IFOREST(I, -4,  12),I=1,2)/ -3, -2/
C     Diagram 13, Amplitude 13
      DATA MAPCONFIG(  13)/  13/
      DATA (IFOREST(I, -1,  13),I=1,2)/  4,  3/
      DATA SPROP(  -1,  13)/      22/
      DATA (IFOREST(I, -2,  13),I=1,2)/  6, -1/
      DATA SPROP(  -2,  13)/      -1/
      DATA (IFOREST(I, -3,  13),I=1,2)/  1, -2/
      DATA TPRID(  -3,  13)/       1/
      DATA (IFOREST(I, -4,  13),I=1,2)/ -3,  5/
C     Diagram 14, Amplitude 14
      DATA MAPCONFIG(  14)/  14/
      DATA (IFOREST(I, -1,  14),I=1,2)/  4,  3/
      DATA SPROP(  -1,  14)/      23/
      DATA (IFOREST(I, -2,  14),I=1,2)/  6, -1/
      DATA SPROP(  -2,  14)/      -1/
      DATA (IFOREST(I, -3,  14),I=1,2)/  1, -2/
      DATA TPRID(  -3,  14)/       1/
      DATA (IFOREST(I, -4,  14),I=1,2)/ -3,  5/
C     Diagram 15, Amplitude 15
      DATA MAPCONFIG(  15)/  15/
      DATA (IFOREST(I, -1,  15),I=1,2)/  4,  3/
      DATA SPROP(  -1,  15)/      22/
      DATA (IFOREST(I, -2,  15),I=1,2)/  5, -1/
      DATA SPROP(  -2,  15)/       1/
      DATA (IFOREST(I, -3,  15),I=1,2)/  1, -2/
      DATA TPRID(  -3,  15)/       1/
      DATA (IFOREST(I, -4,  15),I=1,2)/ -3,  6/
C     Diagram 16, Amplitude 16
      DATA MAPCONFIG(  16)/  16/
      DATA (IFOREST(I, -1,  16),I=1,2)/  4,  3/
      DATA SPROP(  -1,  16)/      23/
      DATA (IFOREST(I, -2,  16),I=1,2)/  5, -1/
      DATA SPROP(  -2,  16)/       1/
      DATA (IFOREST(I, -3,  16),I=1,2)/  1, -2/
      DATA TPRID(  -3,  16)/       1/
      DATA (IFOREST(I, -4,  16),I=1,2)/ -3,  6/
C     Number of configs
      DATA MAPCONFIG(0)/  16/
